### PR TITLE
Fix "module not found" error

### PR DESCRIPTION
**Pull request by sbekrin**
This PR fixes next error:

```
Module not found: Error: Cannot resolve 'file' or 'directory' ./package in <...>/node_modules/7zip
```

### CODE REVIEW

**Comment by fritx** [comment]
@sergeybekrin thanks!
But all was well on my side, what's your os platform and node version?

**Comment by sbekrin** [comment]
@fritx ops, forgot to mention. I'm using macOS, project built via webpack.
Original module using this sub-dependency is `electron-devtools-installer`, I guess.

Versions are:

```
node -v
v6.2.0
npm -v
3.8.9
```

**Comment by fritx** [comment]
It's hard for me to reproduce on MacOS either with node4 or node6.
Maybe it has something to do with webpack.
Anyway, thanks for your info.

**Comment by fritx** [comment]
Ah it was a webpack config problem :))
https://github.com/MarshallOfSound/electron-devtools-installer/pull/60#issuecomment-320231780

**Comment by debuggerpk** [comment]
actually i am getting the same error with typescript and rollup.

**Pull request merged**
